"""create sprints and issue.sprint_id

Revision ID: 812b101cdc96
Revises: b12d26c01e1d
Create Date: 2026-07-10 11:14:43.308938

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "812b101cdc96"
down_revision: str | None = "b12d26c01e1d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_FK_ISSUES_SPRINT = "fk_issues_sprint_id_sprints"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sprints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("goal", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "FUTURE",
                "ACTIVE",
                "COMPLETED",
                name="sprint_status",
                native_enum=False,
                length=20,
            ),
            server_default="future",
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("order", sa.Float(), server_default="0", nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("committed_points", sa.Integer(), server_default="0", nullable=False),
        sa.Column("completed_points", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sprints_project_id"), "sprints", ["project_id"], unique=False)
    op.add_column("issues", sa.Column("sprint_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_issues_sprint_id"), "issues", ["sprint_id"], unique=False)
    op.create_foreign_key(
        _FK_ISSUES_SPRINT, "issues", "sprints", ["sprint_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(_FK_ISSUES_SPRINT, "issues", type_="foreignkey")
    op.drop_index(op.f("ix_issues_sprint_id"), table_name="issues")
    op.drop_column("issues", "sprint_id")
    op.drop_index(op.f("ix_sprints_project_id"), table_name="sprints")
    op.drop_table("sprints")
    # ### end Alembic commands ###
